### ISSUE TITLE
Doubts about the definition

### ISSUE THREAD

**Issue by fusiming3** [changlin31/DNA#18]
Thanks for your codes!
    I have a question that about the definition of  _potential(supernet,teacher=None,eval_loader=None, loss_fn=None,args=None, stage=None,stage_model_pool=None, use_target=False,reset_data=None) in DNA/searching/dna/distill_train.py /      Why the BN layer in the teacher and supernet should be trained separately？In my mind, the  BN layer is fixed in evaluate stage.
    What is more,  the method of searching the model pool is complex. How the model pool is updated in definition of _train_stage in DNA/searching/dna/distill_train.py ?

**Comment by changlin31** [comment]
Hi, @fusiming3 

1. BN layers are _not_ trained but recalibrated before evaluation. 
The BN statistics (running_mean _μ_ and running_var <img src="https://render.githubusercontent.com/render/math?math={\sigma}^{2}">) accumulated during supernet training are not correct. This is because the inputs could come from different paths and also the statistics are not updated in every step. A common technique to fix this is **BN recalibration**, which is defined here:
https://github.com/changlin31/DNA/blob/570c708c950e8bf0a7d5f3dc949163ceb5e49b0a/searching/timm_/utils.py#L338
When performing BN recalibration (or BN correction), the statistics (_μ_ and <img src="https://render.githubusercontent.com/render/math?math={\sigma}^{2}">) of BN layers are reset and recalculated with part of the training set while the weights (_γ_) and the bias (_β_) remain unchanged. After that, the model is set to eval mode and perform evaluation normally. This method is called multiple times in `_potential()`.

2. `model_pool` is a list containing encodings of all possible paths. This list is generated by https://github.com/changlin31/DNA/blob/570c708c950e8bf0a7d5f3dc949163ceb5e49b0a/searching/dna/distill_train.py#L865
and is used when sampling paths for training. By default, `guide_input=True`, so the model pool is  discarded and regenerated before each stage. https://github.com/changlin31/DNA/blob/570c708c950e8bf0a7d5f3dc949163ceb5e49b0a/searching/dna/distill_train.py#L50-L51
